### ISSUE TITLE
Issue when run fredhopper_full_export

### ISSUE THREAD

**Issue by jlyu-forevernew** [aligent/magento2-fredhopper-indexer#10]
Hi, I am having an issue while running fredhopper_full_export, which shows 
"Uncaught TypeError: Aligent\FredhopperIndexer\Model\Export\Data\Meta::getCategoryDataWithChildren(): Argument #1 ($category) must be of type Magento\Catalog\Model\Category, null given, called in /app/wh2okhswlvpuo_stg2/vendor/aligent/magento2-fredhopper-indexer/Model/Export/Data/Meta.php on line 351 and defined in /app/wh2okhswlvpuo_stg2/vendor/aligent/magento2-fredhopper-indexer/Model/Export/Data/Meta.php:359"

**Comment by aligent-lturner** [comment]
Issue was a result of configuration not being complete - closing.
